export default {
  SET_USER: "SET_USER",
  ADD_DEVICE: "ADD_DEVICE",
  SET_DEVICE: "SET_DEVICE",
  SET_DEVICE_INACTIVE: "SET_DEVICE_INACTIVE",
  SET_DEVICE_ACTIVE: "SET_DEVICE_ACTIVE",
  DELETE_DEVICE: "DELETE_DEVICE",
  SET_USER_UUID: "SET_USER_UUID",
  SET_METRIC: "SET_METRIC"
};
